### ISSUE TITLE
About the data splits

### ISSUE THREAD

**Issue by luoxin13** [mathilde-b/TTA#1]
Hello, thanks for sharing your great work!

I am wondering how you separate the dataset into training and validation splits.

It's mentioned in the paper that 19 scans were used for training, one for validation, and 10 scans for testing.

So if convenient, would it be possible to share the Prostate dataset's split file?

BTW. In the SAML repo, each .nii.gz file contains 15~24 slices. Did you directly split them into [384*384] images?

**Comment by mathilde-b** [comment]
Hello, I will see if I can find the data split, thanks !

**Comment by mathilde-b** [comment]
Hey, so these were used for testing : ['Case22','Case17','Case26','Case05','Case02','Case07','Case08','Case12','Case15','Case20']

The rest for training / val !

I have added a make file which may make things easier.
Cheers !

**Comment by luoxin13** [comment]
> Hey, so these were used for testing : ['Case22','Case17','Case26','Case05','Case02','Case07','Case08','Case12','Case15','Case20']
> 
> The rest for training / val !
> 
> I have added a make file which may make things easier. Cheers !

Thanks for your kind reply!
