### ISSUE TITLE
Missing diffmoments

### ISSUE THREAD

**Issue by hariharanrav** [mathilde-b/TTA#2]
![image](https://user-images.githubusercontent.com/75911061/195428365-d40fb593-007a-4c6f-bc6c-9ee3b7f698b7.png)

Hi,

congratulations on a great work! When i tried to replicate, I found that a module was missing. Could you upload the same?

**Comment by mathilde-b** [comment]
Sorry, I just added it !

**Comment by hariharanrav** [comment]
> Sorry, I just added it !

Thank you. Could you please "make files" available for this repository like your other ones? I'm experimenting with prostate data and it will be helpful to get your make file.

**Comment by mathilde-b** [comment]
Hey, I just added a make file. Might be a bit rough still, let me know if it works! 
Cheers

**Comment by hariharanrav** [comment]
Hi, Sorry for not getting back earlier!

I pulled the new version and tried using the make file you shared, it seems to be looking for some pkl files. Could you kindly let me know what I could be missing?

![image](https://user-images.githubusercontent.com/75911061/201489518-84603b3e-dbcc-43a1-a189-a32065f8fc23.png)

**Comment by mathilde-b** [comment]
Hello !
This is weird, with the makefile as is, you should have --model_weights="" for the source training (meaning, start from random weights), so it should not enter line 52 in main.py .
I just changed a default parameter in main.py, let me know if it works now !
